title: Anxin (Bob) Guo   <br>郭岸新
logo: /assets/Selfie.jpg
description: bobguo2023[At]u[Dot]northwestern[Dot]edu
remote_theme: pages-themes/minimal@v0.2.0
url: "https://anxin-bob-guo.org"
plugins:
  - jekyll-remote-theme 
  - jekyll-sitemap
  - jekyll-seo-tag